### ISSUE TITLE
Conditional tags evaluate 0 as true, which may be an unexpected corner case

### ISSUE THREAD

**Issue by Frencil** [statgen/locuszoom#103]
In #101 the `{{#if foo}}{{/if}}` conditional was changed such that the value (`foo`) is evaluated as true when `0`. This solves the immediate problem that arises when using the conditional tag for determining if a field is populated with any value but may break expected behavior should a value of `0` need to be evaluated as false.

A potential solution would be to expand the conditional tag to optionally support an operator and comparison value, allowing for more explicitly defined behavior.

**Comment by pjvandehaar** [comment]
The functionality I want is `foo || foo===0`.  I can't think of a good syntax to represent that, except for `{{#if foo|true_or_0}}`.

**Comment by pjvandehaar** [comment]
Currently, we parse templates with
```
/\{\{(?:(#if )?([A-Za-z0-9_:\|]+)|(\/if))\}\}/;
```
but the new regex will be:
```
id='[A-Za-z0-9:|_]+'
thing='(?:' + id + '|"(?:[^"]|\\\\")*"|[0-9]+)'
op = '(?:===|!==|<|>)'
expr = '(?:' + '\\s*'+thing+'\\s*' + '|' + '\\s*'+thing+'\\s*'+op+'\\s*'+thing+'\\s*' + ')'
disjoint = '(?:' + expr + '(?:\\|\\|' + expr + ')*)'
ifregex = '{{#if ' + disjoint + '}}'
varregex = '{{' + id + '}}'
endifregex = '{{/if}}'
(new RegExp( ifregex +  '|' + varregex + '|' + endifregex)).exec('{{#if x === 0 }}x')
```

**Comment by Frencil** [comment]
I'd propose a third option; something that let's basic conditionals use expected javascript evaluations of truthiness but allow for an explicit "is defined" check (maybe something along the lines of `{{#ifdefined {{var}}}}...{{/ifdefined}}`). In your use case here it seems you only care about showing something if it's defined and don't really care about its value if it is, so maybe expanding out the conditional logic to allow for operators and compound conditionals is an overkill approach to a much simpler problem.

**Comment by pjvandehaar** [comment]
But, I don't want empty strings.

**Comment by Frencil** [comment]
`{{ifnotempty {{var}}}}...{{/ifnotempty}}`?

Certainly gargantuan regexes are an indication that we're *not* heading in the right direction. A more explicit tag that is purpose-built and can be clearly documented with clean syntax is going to play much nicer for clarity and long term maintainability.

**Comment by pjvandehaar** [comment]
I like `{{#ifnotempty foo}}`.  

| value | js | what I want |
| --- | --- | --- |
| 0 | falsy | *truthy* |
| "" | falsy | falsy |
| "x" | truthy | truthy |
| [] | truthy | *falsy* |
| {} | truthy | *falsy* |
| 1 | truthy | truthy |
| true | truthy | truthy |
| false | falsy | falsy |
| null | falsy | falsy |
| NaN | falsy | falsy? |
| undefined | falsy | falsy |

**Comment by Frencil** [comment]
In response to the table my assumptions about what "not empty" means would differ with yours for `[]` and `{}` and could really see `NaN` going either way. The term is clearly too ambiguous, so isn't a viable solution to this problem.

At this point I'd be wary of overcomplicating this issue. We've solved the immediate problem for PheWeb's use case, and the behavior is well documented. Let's let it be until an actual use case for 0-falsey behavior presents itself.
