### ISSUE TITLE
Tooltips on annotation track do not show in "merged tracks" mode

### ISSUE THREAD

**Issue by welchr** [statgen/locuszoom#106]
How to reproduce: 

1. Go to http://locuszoom.org/locuszoomjs.php
2. Add a dataset (I used DIAGRAMv3)
3. Add bed track (I used ENCODE / chromHMM / Chromatin State Segmentation by HMM from ENCODE/Broad)
4. Hover over segments of track - tooltip will show
5. Click "merge tracks" 
6. Hover over segments - tooltip will not show

**Comment by Frencil** [comment]
Bug confirmed. Likely a regression (I swear tooltips worked on collapsed bed tracks initially...) from the other tooltip work that's happened recently. Will take a look.

**Comment by Frencil** [comment]
Issue resolved in #116.

**Comment by abought** [comment]
PR merged, closing issue. Thanks again!
