### ISSUE TITLE
Prebuilt LDLZ, GeneLZ, RecombLZ, etc.

### ISSUE THREAD

**Issue by charliecurnin** [statgen/locuszoom#109]
One of the things that's made getting started with LocusZoom so nice is that it comes with the sample data in `/locuszoom/staticdata`. 

The `ld_...`, `genes_...`, `recomb_...`, and `constraint_...` jsons have been particularly helpful, but they only provide data for `10:114550452-115067678`. I'm wondering if there are similar resources available (from LocusZoom or some other source that can be integrated easily into LocusZoom), for the entire genome. 

As I understand it (this may be entirely wrong), the only type of Data Source I have to provide from my GWAS is an `AssociationLZ`; the other sources (`LDLZ`,`GeneLZ`,`RecombLZ`, `ConstraintLZ`, etc.) that add information and functionality to the plot just provide information that can be used by me or anyone else to visualize our results (provided the other sources actually have information on the genes and region in which the variants we want to show are located).

**Comment by abought** [comment]
Thanks for the suggestion- we're always looking for ways to help people get started. Below are some suggestions courtesy of my colleagues.

Specifically, you may want to check out our publicly accessible APIs if you haven't already. These APIs currently power some of the examples in the repo, and can be used to access more genome data. Here are some links to get you started- please note that the docs may be slightly out of date.

[API docs](http://portaldev.sph.umich.edu/docs/api/v1/#overview-of-api-endpoints)
[A complex sample plot](http://statgen.github.io/locuszoom/examples/multiple_phenotypes_layered.html) (with [code](https://github.com/statgen/locuszoom/blob/master/examples/multiple_phenotypes_layered.html#L67))

You can also see some of these APIs in action in our interactive demo.
http://locuszoom.org/locuszoomjs.php

**Comment by abought** [comment]
Hey there! Just following up on this issue, as it's been a while. We'd certainly be curious to know if this helped you- I'm going to close this issue for now, but feel free to reopen if it didn't address your question.

In the future we are investigating adding more datasources that can be used with other data formats or endpoints. Because Locuszoom is extensible, you can also write your own as needed.
