### ISSUE TITLE
Fix or retire plot builder

### ISSUE THREAD

**Issue by Frencil** [statgen/locuszoom#118]
Plot builder has grown stale. Evaluate:

* What it would take to update (and maintain going forward)
* Efficacy of plot builder as a tool in general (should we even keep it?)
* If it's worth keeping/updating, how to integrate it into the static site so that it'd more discoverable.

**Comment by abought** [comment]
Stepping back to look at the big picture, the broad problem we are trying to solve is how to help people visualize their own data. 

Based on user feedback, it seems that our example gallery has been very successful at helping developers discover to use features. For end users/ analysts, [locuszoom-tabix](https://abought.github.io/locuszoom-tabix/) is providing a point and click way to explore specific functionality. 

I'll retire the builder as of 0.9, to focus our efforts on those more user-oriented tools.
