### ISSUE TITLE
Mousewheel zooming on data layers

### ISSUE THREAD

**Issue by Frencil** [statgen/locuszoom#17]
** Depends on #15 and #16**

When a user mouses over a data layer and scrolls with their mouse wheel the data layers should "zoom" by changing the x range of the visible data set.

Based on a previous discussion with Broad developers the desired default behavior would be to scale the y range on the positions panel to fit all data regardless of the previous view's y range.

## Estimate

This feature will probably take two weeks of development to build and test.

**Comment by MrFlick** [comment]
This should probably also include "pinching" on mobile devices.
