### ISSUE TITLE
Allow users to filter genes track by biotype

### ISSUE THREAD

**Issue by abought** [statgen/locuszoom#199]
Replaces #18 

# Purpose
Our plot has limited room to display genes in a standard figure, and some users have suggested that it might be nice to intelligently choose which elements are shown, as not all gene entries are of equivalent broad interest (see: [gencode list of biotypes](https://www.gencodegenes.org/human/stats.html)). For example, the PheWeb nearest gene annotator uses a specific [subset](https://github.com/pjvandehaar/genelocator/blob/master/genelocator/download.py#L20-L37) of options.

The new LZ filtering feature can be used to render only user-selected biotypes.

Requirements:
- [x] The portaldev API server will need to expose gene biotype field
- [ ] A `display_options` dropdown menu will need to be added to the genes track with a sample biotype field. We should identify what the most relevant groups of genes to show are- ideally 1-5 preset groups.
- [x] Add new "in" and "match" filter functions to allow search-like behavior with filters.
- [x] Modify genes track rendering to perform layout on filtered dataset. (instead of leaving space for the hidden elements as it currently does)

Rather than allowing the user to drag and reorder genes, they would thus be selecting the data to render based on the intended meaning/ most common use case.

**Comment by abought** [comment]
Goncalo suggests a similar list to pheweb.

`protein_coding` category as definite must. Excluding pseudogenes would be nice; might want to include mirnas. ig c/d/g good to include. For RNA, keep Mt_tRNA, Mt_rRNA.

A long term stretch goal would be a checkbox list for fine grained control.

**Comment by pjvandehaar** [comment]
For reference, here are the counts on hg38 for gencode v29:

```
19940	protein_coding
144	IG_V_gene
106	TR_V_gene
79	TR_J_gene
37	IG_D_gene
18	IG_J_gene
14	IG_C_gene
6	TR_C_gene
4	TR_D_gene
22	Mt_tRNA
2	Mt_rRNA
52	rRNA
8	ribozyme
# Total: 20432

7635	lincRNA
5587	antisense
2213	misc_RNA
1900	snRNA
1881	miRNA
1060	TEC
943	snoRNA
895	sense_intronic
601	processed_transcript
180	sense_overlapping
73	bidirectional_promoter_lncRNA
49	scaRNA
32	3prime_overlapping_ncRNA
5	sRNA
2	non_coding
1	scRNA
1	macro_lncRNA
1	vaultRNA
# Total: 23059

10196	processed_pseudogene
2649	unprocessed_pseudogene
886	transcribed_unprocessed_pseudogene
500	rRNA_pseudogene
481	transcribed_processed_pseudogene
188	IG_V_pseudogene
124	transcribed_unitary_pseudogene
95	unitary_pseudogene
41	polymorphic_pseudogene
33	TR_V_pseudogene
18	pseudogene
9	IG_C_pseudogene
4	TR_J_pseudogene
3	IG_J_pseudogene
2	translated_processed_pseudogene
1	IG_pseudogene
# Total: 15230
```

**Comment by abought** [comment]
Thanks Peter- these counts could be useful if we decide to add more than two groups of filters. (which I think might become a real user request after release)

I'll push a new release to my.locuszoom.org tomorrow AM with this feature, so we can get real user feedback!
