### ISSUE TITLE
How to change the legend on the y-axis?

### ISSUE THREAD

**Issue by CFB2018** [statgen/locuszoom#210]
Hi, 
I was wondering if it is possible to change the legend on the y-axis?  The default is -log10 Pval. How do I go about changing that label?
Thank you, 
Carmen

**Comment by abought** [comment]
There is no UI for people to do this in the web browser, but if you are creating your own custom website that uses LocusZoom.js, this can be done via the layout object (which has an awful lot of config options!)

For example, in the standard LZ association plot view, the scatter plot is the first panel (row), and the label you refer to  is the left hand axis (axis y1). So by digging through the nested layout object, you'd set the configuration option you want as follows:

`layout.panels[0].axes.y1 = "my custom label";`

We're starting from the layout object used to render the plot (`LocusZoom.populate("#plot", data_sources, layout)`), and only modifying one specific field while leaving the rest unchanged. Obviously this is easier to do if you change the label before rendering the plot.

LocusZoom objects have, um, a lot of configuration options, which can be overwhelming at first. It can be helpful to explore this interactively (eg through the browser devtools console) We are actively looking to make the process of custom layouts more approachable and ideas are welcome.

**Comment by CFB2018** [comment]
Ok, thank you very much for your reply. I will look in to it some more.
Kind regards,
Carmen

**Comment by abought** [comment]
Good luck! I'm closing this issue for now. If you have followup questions, please feel welcome to reopen the ticket as needed.
