### ISSUE TITLE
Save PNG with name based on search and search button

### ISSUE THREAD

**Issue by C-Gouveia** [statgen/locuszoom#255]
Hi! This is a feature request. 

It would be nice if, when an image is saved, in regional locus zooms, if it had the search performed incorporated in the name, instead of being named only as "locuszoom (3).png"

It would also be nice to be able to search in regional locus zooms by pressing enter, instead of having to press the button every time.

Thank you very much,
Best,
Catarina

**Comment by abought** [comment]
Hi there! I've updated localzoom to allow search by enter key.

A dynamic filename is a neat idea but not immediately on the radar. I'll continue mulling over the best way to do this, even though the current ticket may be closed.
