### ISSUE TITLE
Missing SNP but LD pattern present

### ISSUE THREAD

**Issue by jcabanad** [statgen/locuszoom#263]
Hi,

I'm using your webpage to do some regional plots and I found this situation in one specific region. I have an LD pattern but I don't have the SNP I'm looking for. I don't know if it could be that I don't have this SNP in your reference panel or a bug. Can you please help me.
Best,

Judit

<img width="1107" alt="Captura de Pantalla 2021-12-10 a les 16 48 49" src="https://user-images.githubusercontent.com/72014700/145601929-08e44b9b-74e7-4f69-9bf4-301fb3c5bd5b.png">

**Comment by abought** [comment]
Thanks for the question! The UI is perhaps a bit confusing. I'll try to think of ways to make that easier, and would welcome suggestions based on the description below:

1. The "Go to region" box finds a position around the specified variant, but it does not ask whether that variant is in a specific study, or tell the plot to do anything else specific to that variant.
2. Once in a region, it draws LD based on either the most significant variant in that region, OR a user-selected variant (each data element has a tooltip with "make ld reference variant" button).
