### ISSUE TITLE
JS formatter

### ISSUE THREAD

**Issue by sir4ur0n** [statgen/locuszoom#278]
Please document the JS formatter to use on LocusZoom code base (I guess somewhere in https://github.com/statgen/locuszoom#development-setup) and - if applicable - provide the formatter configuration file :pray:

**Comment by sir4ur0n** [comment]
Apparently, **some** formatting at least can be achieved with `eslint --fix esm/ test/` (e.g. for indentation inside an `if` block), but I don't know if this covers every formatting concern?

**Comment by abought** [comment]
As you suspected, the formatter we use is `eslint`. We [check](https://github.com/statgen/locuszoom/blob/develop/package.json#L34) it for relevant code files (and verify this in [CI](https://github.com/statgen/locuszoom/blob/develop/.github/workflows/node.yml#L42)).

All format rules should be applied correctly using the `--fix` command, detecting correct options from the provided [.eslintrc](https://github.com/statgen/locuszoom/blob/develop/.eslintrc.js) config file in this repo- I'll try to add the auto-fix command to the README. In theory someone could create a simple pre-commit hook to do this for their own setup; I use an editor (pycharm) that runs eslint and warns me as I work.

If you're seeing different rules in CI vs locally, it's possible that you are using a globally installed version of eslint that is older/newer, and applying different rules. If that's the case let me know and it's worth following up.
