### ISSUE TITLE
Inconsistent gene names found in UMich data API

### ISSUE THREAD

**Issue by vb-tony** [statgen/locuszoom#292]
Hello,

This is an observation with regards to the genes annotations endpoint **GET /annotation/genes/** of the UMich data API. I wasn't sure who owned the API but since it is used by LocusZoom (which is why we use it as well), I figured I could start here. Please let me know if I should direct this to another contact. 

This is **super low priority** but a teammate of mine noticed that a couple of the genes have outdated names. 

Specifically:
- Gene ID [ENSG00000237517](https://useast.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000237517;r=22:18985836-18994501;t=ENST00000399539) is CELSR1P1 as opposed to DGCR5  
- Gene ID [ENSG00000240849](https://www.ensembl.org/Homo_sapiens/geneview?gene=ENSG00000240849) is PEDS1 as opposed to TMEM189

Again, nothing major but figured it didn't hurt to mention. If it doesn't make sense to do any changes or updates, that's okay as well. Or if I need to direct this to a different department, happy to do that too.

Thanks!

**Comment by welchr** [comment]
Apologies. The API is outdated and only has up to GENCODE v35. It will likely not be updated in the future due to funding constraints. The API code is here: https://github.com/statgen/locuszoom-api.
