### ISSUE TITLE
gene annotation and missing LD

### ISSUE THREAD

**Issue by yu-zhang-oYo** [statgen/locuszoom#294]
Hi, I have a couple of questions regarding the settings for gene annotation data and LD information in LocusZoom:

1. After using the online version of LocusZoom at https://my.locuszoom.org/ (GRCh38 build), I noticed that some of the gene annotations under the regional plot differ from those in plots generated with the locuszoomr package. I understand that locuszoomr uses the ‘EnsDb.Hsapiens.v86’ Ensembl database. Could you please let me know which database the online version uses? I am not sure if this difference is marginal.

2. In one of the regional plots generated through the online version, all the dots appear in grey (the most significant SNP as the index SNP). However, in the locuszoomr plot, some dots are colored with LDlink. Could you clarify the LD information source used in the online version and explain why all the dots are grey in the online plot? How can I make those SNPs has LD data?

Any guidance or clarification would be greatly appreciated.

**Comment by abought** [comment]
Thanks for the question. Per missing LD:
https://my.locuszoom.org/about/#missing-ld

The online version may be using an old version of the genes database. I moved on from the project several years ago, and I simply am not in a position to comment on whether or not they have staffing for ongoing updates.

I was not aware of the [R package](https://github.com/myles-lewis/locuszoomr); interesting!

**Comment by yu-zhang-oYo** [comment]
Thanks for the reply. I thought the locuszoomr has the same development team as the online version. If it is possible, could you please guide me on how to find the source of LD and genes database the online version uses? in the someplace of github or other place? Thanks


> Thanks for the question. Per missing LD: https://my.locuszoom.org/about/#missing-ld
> 
> The online version may be using an old version of the genes database. I moved on from the project several years ago, and I simply am not in a position to comment on whether or not they have staffing for ongoing updates.
> 
> I was not aware of the [R package](https://github.com/myles-lewis/locuszoomr); interesting!

Thanks for the reply. I thought the locuszoomr has the same development team as the online version. 

If it is possible, could you please guide me on how to find the source of LD and genes database the online version uses? in the someplace of github or other place? Thanks

**Comment by abought** [comment]
Never heard of the R package until I went looking!

The Ld data is described via API endpoints documented here (click "references" and "populations" for sample queries)
https://portaldev.sph.umich.edu/playground

For genes data, according to another ticket, the API contains GENCODE v35. My wonderful former colleague suggests it may not be updated regularly due to funding/staff constraints.
https://github.com/statgen/locuszoom/issues/292
