### ISSUE TITLE
Document how to build custom Data Sources with different URL structures

### ISSUE THREAD

**Issue by Frencil** [statgen/locuszoom#37]
# The Problem

Presently data sources are implicitly assumed to be API endpoints that can only be accessed via an HTTP request with a [rather specific](https://github.com/statgen/locuszoom/blob/master/assets/js/app/Data.js#L154) URL structure. As LocusZoom is considered a candidate for pulling from other data sources we may need to support more generic methods for defining request URL composition.

@pjvandehaar - please comment here about the URL structure for data requests in Bravo, or wherever you may be considering plugging in LocusZoom. Seeing how those URLs must be composed, compared to how LocusZoom is currently built, will help demonstrate more generic methods.

**Comment by pjvandehaar** [comment]
Right now, the two that LocusZoom will be consuming are:
- browser.sph.umich.edu/api/coverage/region/22-46546715-46615880
- browser.sph.umich.edu/api/variants_in_region/22-46546715-46615880

Maybe we'll add a GET param on the second to tell it which attributes we want (pos, CADD, etc).

Perhaps I'll need to make a genes API as well.

If you want to stick to the current structure, it should be easy enough to implement.  Flask plays nicely with delimiting variables by slashes, so that's what I do.

**Comment by Frencil** [comment]
**Update:** so with discussion it looks like our approach for now is to not worry too much about making the `getURL()` method (or data source end point URL composition) more generic, but instead have implementers of the plugin define their own custom `getUrl()` methods to suit their needs.

I've changed the tags on this issue then to mark it as a **Documentation** need.

**Comment by pjvandehaar** [comment]
That makes sense.  I'm happy with that.

**Comment by Frencil** [comment]
@MrFlick - just poking this issue. The [documentation](https://github.com/statgen/locuszoom/wiki/API-Reference) has matured considerably to keep pace with how the layout concept has matured, but data sources documentation is still missing.

The need for this came up this week when trying to build a new data source for fetching PheWAS data for individual variants. @pjvandehaar and I came up with a workable solution (code [here](https://github.com/statgen/michigangenomics/blob/master/js/mgi_phewas.js)), but it doesn't use `LocusZoom.DataSources.prototype.addSource()` to create it. Instead it adds the new data source the same way the existing data sources are defined. Maybe we just need to sit down some time and iterate over Data.js in general? Either way, I want to figure out the right way to build new data sources now that we've effectively done it four times, get it into the documentation, and hopefully iterate over the workflow to make the syntax as clear and intuitive as possible.

**Comment by MrFlick** [comment]
I've added some basic documentation about how data sources work and how to create custom sources.
