### ISSUE TITLE
Smarter responsive resizing modes

### ISSUE THREAD

**Issue by Frencil** [statgen/locuszoom#43]
This is the continuation of a discussion started in #41 with @MrFlick and @benralexander.

Presently resizing can be none, manual, or _responsive_, which keeps a fixed aspect ratio.

It has been suggested that _responsive_ could manifest in a few different ways, depending on the end use case. For example:
- Keep the plot height constant but allow for aspect ratio to adjust as the container adjusts (i.e. responsive only in the x dimension)
- Have a more dynamic aspect ratio that mimics that of the page itself. This would be useful in the case of a tablet or phone displaying a plot and changing between portrait and landscape.

Are there other "responsive" modes we can think of? Both of these would be straightforward to implement. New layout syntax would be required.

**Comment by pjvandehaar** [comment]
I like the approach with fixed height and dynamic width.  I've implemented this by removing the `this.layout.height`-related code at https://github.com/statgen/locuszoom/blob/f33885b2f22242de021f47776602d7d8e5d4e647/assets/js/app/Plot.js#L424 and adding `&& false` to the condition at https://github.com/statgen/locuszoom/blob/f33885b2f22242de021f47776602d7d8e5d4e647/assets/js/app/Plot.js#L462 .

What is the right layout parameter for this?  Perhaps `layout.responsive_resize = "width-only"`, and keep `layout.responsive_resize = true` as an alias for `layout.responsive_resize = "preserve-aspect-ratio"`?

**Comment by abought** [comment]
Following up on a slack discussion: I'm open to this idea, and the idea of backwards-compatible configuration seems reasonable. 

Peter has volunteered to put together an initial pull request for review and followup/ testing.

**Comment by abought** [comment]
As this is the last major bugfix needed for 0.9, I've put together a candidate PR.

Peter, I got the sense you were experimenting, and that perhaps there were more requirements than our original notes. Are there any test cases you'd like to see considered?
