### ISSUE TITLE
Evaluate d3 v4.x and potentially upgrade

### ISSUE THREAD

**Issue by Frencil** [statgen/locuszoom#72]
In June 2016 a rare major release for [d3](https://github.com/d3/d3) dropped: version 4.x. Just about every corner of the library was touched in some way.

There may be useful new features and/or a performance benefit to upgrading. Or it could be a massive time sink that doesn't yield any appreciable benefit. Either way, given the scale of the changes between d3 3.x and 4.x and LocusZoom's current use of d3 as a core dependency, it should be evaluated.

**Comment by abought** [comment]
Had a chat with Chris a while back. 

From the sound of it, this would be a larger task, and for right now our efforts will focus elsewhere. Closing this issue for now, but we can reevaluate in the future and reopen as warranted.
