### ISSUE TITLE
Add Code Coverage Reports

### ISSUE THREAD

**Issue by Frencil** [statgen/locuszoom#8]
It would be nice to get code coverage reports for our automated tests, and possibly also have those reports consumed by a service like [Coveralls](https://coveralls.io/) to track our coverage level over time.

Early attempts to hook up the gulp/mocha build/test process to some coverage reporting today proved less than fruitful. Istanbul is a viable node package for coverage reports but I could only get it to work command line separately (read: not in gulp context) and even then our coverage levels were dinged since dependencies (d3 and Q) were being counted against our totals. Will revisit in the future.

**Comment by abought** [comment]
Implemented as part of #189, with the switch to webpack/true modules.
