### ISSUE TITLE
Methods to view/export underlying data

### ISSUE THREAD

**Issue by Frencil** [statgen/locuszoom#80]
From the next round of goals for the T2D Portal:

> Enhance LocusZoom to support tabular views of data for integration with the other new tables on the gene page

Groundwork for this could be API methods to provide data on a per-data-layer basis is JSON and/or CSV. These methods will need to implement sanitization logic to ensure JSON is clean and CSV is coherent.

That alone may be sufficient for the T2D Portal, but it may also be worthwhile to build a dashboard component to provide UI for those API hooks to enable raw data downloads.

**Comment by Frencil** [comment]
Latest master has a first pass at this, tested and functional. Methods provide for JSON, CSV, and TSV exports. Still need to better handle ciruclar references and get feedback on use cases, so leaving this open for now.

**Comment by abought** [comment]
Ticket #123 would also cover part of this via the `subscribeToData` mechanism for dynamic data access. (live updating otherr widgets on that page)

Tagging here to track.
