### ISSUE TITLE
firefox issue and suggestions

### ISSUE THREAD

**Issue by baoxingsong** [statgen/locuszoom#81]
1. "Press [SHIFT] while scrolling to zoom" does work on Firefox v 50.0.2.
2. It would be great if you include functions like Navigate buttons, search by gene name box and go to region box in examples.

**Comment by Frencil** [comment]
Thanks for the suggestions, @baoxingsong. The latest LocusZoom.js release (v0.5.2) fixes the Firefox scroll issue and introduces built-in components for navigation buttons (see http://statgen.github.io/locuszoom/ for an example).

I have not yet added a go-to-region box in built-in components but that shouldn't take too much to do.

A search by gene box, though, is not something that can be implemented purely client-side. It would require talking to a service with a database of gene names and regions, and even then the results could vary depending on other factors such as which transcriptions you'd want to use. Thus that feature remains something that, if your application requires it, you may need to implement yourself.
