### ISSUE TITLE
Expand template markup to allow for conditional blocks

### ISSUE THREAD

**Issue by Frencil** [statgen/locuszoom#86]
As described by @pjvandehaar it would sometimes be useful, when available fields may vary from element to element in a single data layer, to write the general tool tip markup such that certain sections would only be displayed if the field is present on the element.

Note that handlebars.js, which was the inspiration for the double-curly markup notation in LocusZoom templates, does have a [convention](http://handlebarsjs.com/builtin_helpers.html) for conditionals, among other things.

**Comment by pjvandehaar** [comment]
What's your opinion on Mustache's syntax? http://mustache.github.io/#demo .  It allows iteration over an array of objects.

**Comment by pjvandehaar** [comment]
PR https://github.com/statgen/locuszoom/issues/86

**Comment by Frencil** [comment]
Implemented on [v0.5.6](https://github.com/statgen/locuszoom/releases/tag/v0.5.6)
