### ISSUE TITLE
Make mouse guides toggle-able via layout

### ISSUE THREAD

**Issue by Frencil** [statgen/locuszoom#96]
As documented in [this issue](https://github.com/statgen/pheweb/issues/61), sometimes mouse guides aren't wanted. They should still be on by default, but should be hooked to a layout directive (at the plot level) that can be set to false to prevent them from rendering.

**Comment by pjvandehaar** [comment]
1. Make all `layout`s have `.mouse_guide = true` by default.
2. Make `Plot.initialze` only do things related to `mouse_guide` if `layout.mouse_guide`.
    - it would be cleaner if the `this.mouse_guide` and the `this.interaction.dragging` parts of `mousemove` were in separate functions.  Then all `mouse_guide` code could be in one `if` block.
3. Set `layout.mouse_guide = false` in `LZ.Layouts.get('plot', 'standard_phewas').

**Comment by pjvandehaar** [comment]
I just edited https://github.com/statgen/locuszoom/wiki/Plot
